language: python
sudo: false
python:
  - "pypy3"
env:
  - TRY=1
  - TRY=2
  - TRY=3
  - TRY=4
install:
    - pip install -vr requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install > /dev/null
  - supybot-test -v --no-network --disable-multiprocessing plugins/Web plugins/Network plugins/Lart plugins/Note plugins/Factoids plugins/Reply plugins/Config plugins/ChannelStats plugins/Status plugins/String plugins/Format plugins/MoobotFactoids plugins/NickAuth plugins/Utilities plugins/Channel plugins/Anonymous test plugins/News plugins/MessageParser plugins/Later plugins/BadWords plugins/Plugin plugins/Admin plugins/Dunno plugins/GPG plugins/URL plugins/QuoteGrabs plugins/Alias plugins/Games plugins/Karma plugins/Praise plugins/Time plugins/Aka
notifications:
    email: false
matrix:
  fast_finish: true
